# Use input command to determine updated state and return it

# Goal definition
geometry_msgs/Point source
geometry_msgs/Vector3 ray
bool bidirectional
int8 index

---
# Result definition
geometry_msgs/Point intersect

---
# Feedback definition